Project 1:  Mobile version skeleton
yaseerokino/Portfolio pull request #1
Opened 2021-07-07 19:30 UTC by yaseerokino

## Features Added ♻️ 

- Added a header section for navigation
- Added a headline section, showing an introductory message 
- Used exact color scheme as designed in this [template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122)
- Added hover effect to the menu  navigationbutton on the header section

2021-07-07 19:54 UTC, arslanbisharat requested changes
# Changes Requested, 

Hi @yaseerokino, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-07-07 19:54 UTC, arslanbisharat commented on index.html
> +      <h4 class="logo">OKINO</h4>
- [ ] The logo should be a link. You can make it a link using `a tag`.

2021-07-07 19:54 UTC, arslanbisharat commented on index.html
> +        <i class="fa fa-bars"></i>
- [ ] Please make sure the hamburger has a `nav tag
`

2021-07-07 19:54 UTC, arslanbisharat commented on css/style.css
> +html body {
- [ ] The display should be using `flex` methodology.

2021-07-07 19:54 UTC, arslanbisharat commented on css/style.css
> +.headline {
- [ ] Make sure this section has the proper background image (decorations are always background images, not `images` tags)

2021-07-07 19:54 UTC, arslanbisharat commented on index.html
> +      </div>
- [ ] The list of icons uses a `ul` tag to group them, and `li` per icon; each icon has a link (`a` tag)

2021-07-07 21:07 UTC, yaseerokino commented
Successfully made all the required changes

2021-07-07 21:26 UTC, rloterh commented on index.html
> +      <h4 class="logo">OKINO</h4>
Well resolved.

2021-07-07 21:29 UTC, rloterh commented on index.html
> +        <i class="fa fa-bars"></i>
Well resolved.

2021-07-07 22:04 UTC, rloterh commented on index.html
> +      </div>
Well resolved

2021-07-07 22:25 UTC, rloterh commented on css/style.css
> +.headline {
well resolved

2021-07-07 23:03 UTC, rloterh requested changes
Hi Yaseer, 

You did great on this project, and for making the changes requested by the previous reviewer!👏 👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there!👍 

## Good Points 👍  
- Highly organized/clean code
- Good ReadMe
- No linter errors


## Required Changes ♻️
- [ ] _Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
__As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 1 more limited review per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).__

2021-07-07 23:23 UTC, yaseerokino commented on css/style.css
> +.headline {
Thank you for the feedback, although I did not set a specific width for the background image

2021-07-07 23:27 UTC, yaseerokino commented on css/style.css
> +  background-position: center center;
Update my CSS, changed the background-size property to **cover**, and added a background-position of **center**

2021-07-07 23:27 UTC, yaseerokino commented on css/style.css
> +.headline {
Updated my CSS, changed the background-size property to **cover**, and added a background-position of **center center**

2021-07-07 23:29 UTC, yaseerokino commented on css/style.css
> +.headline {
Also, I'm not sure if I'm allowed to use media queries at this particular stage of the project

2021-07-08 08:46 UTC, carlos-ssh approved these changes
Hi @yaseerokino, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-08 08:46 UTC, carlos-ssh commented on index.html
>  <html lang="en">
[OPTIONAL]
- ADD TO YOUR .GITIGNORE YOUR .DS_Store files. Keep your project professional.

2021-07-08 08:50 UTC, yaseerokino commented on index.html
>  <html lang="en">
I do use one of the generic node .gitignore files, Also should i merge my PR to my main branch

2021-07-08 08:50 UTC, merged